### ISSUE TITLE
DESTDIR support

### ISSUE THREAD

**Issue by stsp** [stsp/build-gcc#1]
I started to implement DESTDIR support:
https://github.com/stsp/build-gcc/commit/1fdd46f766b168e514d919b94914d88bd65992f1
and it works for some components.
But when building gcc, DESTDIR does not
propagate to system headers. What's worse,
gcc uses things like `-isystem` and uses an
absolute prefix path there, so even `--sysroot=`
doesn't help.
@skitt, @jwt27 do you have any suggestions
on how to proceed from here? I don't expect
the debuild support can be added w/o proper
DESTDIR support, or can it?

**Comment by skitt** [comment]
I’m not sure it’s possible to run `gcc` somewhere other than its target installation location. I always end up splitting up my builds when dealing with cross-compilers for packaging... You can work some magic with `-I` and spec files for the linking angle (see [this example in `mingw-w64`](https://salsa.debian.org/mingw-w64-team/mingw-w64/blob/4974e2c222eb722f0dcbf6656732fff6a0f5be50/debian/rules#L153) along with [the matching spec template](https://salsa.debian.org/mingw-w64-team/mingw-w64/blob/master/debian/specs.in)), but I don’t think it’s enough for what you’re trying to do.

The only reliable approach for an “all-in-one” build would be to configure `gcc` for a real installation in `DESTDIR`, and then reconfigure and rebuild it for the target...

BTW see [here](https://tracker.debian.org/pkg/binutils-djgpp) for something interesting ;-).

**Comment by stsp** [comment]
> I’m not sure it’s possible to run gcc somewhere other than its target installation location.

You mean, `--sysroot=` is hopeless even if you
are not building the gcc suite, but also when you use
it? So is it completely unrelocatable? As my impression
was that `--sysroot=` _could_ work, if not for the
absolute pathes in `-B` and `-isystem`.

> The only reliable approach for an “all-in-one” build would be
> to configure gcc for a real installation in DESTDIR, and then
> reconfigure and rebuild it for the target...

Could you please explain what exactly is to do here?
Should I first include DESTDIR into prefix, and then
not include? I probably can build gcc with the prefix
that includes DESTDIR (not that I succeeded from
the first try though), but when I reconfigure it with the
right prefix, how would I rebuild? I guess you mean
something else though, please clarify.

> BTW see here for something interesting ;-).

Indeed but I don't think I have problems building
binutils. :) But in either case, yes, eventually we'd
better build-depend on your packages. But its too
early to speak as no one have yet succeeded in
building gcc with DESTDIR.

Just wondering:
- Is clang any noticeably better on the build?
- Is there any upstream help from gcc devs or
are they completely hopeless?

Looks like we are trying to solve the problems
that are not ours...

**Comment by stsp** [comment]
Maybe @tkchia can take the great pain of fixing
the gcc build? :) It really seems to me that gcc
presents more problems than it solves (in presence
of clang of course), but if someone can just fix it,
it can still be useful.

**Comment by tkchia** [comment]
Hello @stsp,

> Maybe @tkchia can take the great pain of fixing the gcc build? :)

Well, this is a really, _really_ upstream issue ☺ pertaining to the machine-independent parts of GCC.  Probably the GCC mailing lists are better venues for such matters.

Meanwhile, I am pretty sure that I had been able to get Launchpad to create `.deb` packages for `gcc-ia16` for a long time --- something which I believe involves `$(DESTDIR)` support.  (A [build log](https://launchpadlibrarian.net/437731401/buildlog_ubuntu-xenial-amd64.gcc-ia16-elf_6.3.0-20190816.21-ppa190817083~xenial_BUILDING.txt.gz) from a recent build is available.)

May I know what method you are using to specify `$(prefix)` and `$(DESTDIR)` to the GCC scripts?

Thank you!

**Comment by skitt** [comment]
> Meanwhile, I am pretty sure that I had been able to get Launchpad to create `.deb` packages for `gcc-ia16` for a long time --- something which I believe involves `$(DESTDIR)` support. (A [build log](https://launchpadlibrarian.net/437731401/buildlog_ubuntu-xenial-amd64.gcc-ia16-elf_6.3.0-20190816.21-ppa190817083~xenial_BUILDING.txt.gz) from a recent build is available.)

Yes, GCC itself supports `DESTDIR` during installation. As I understand it, @stsp is trying to install GCC using `DESTDIR`, and then run it from there rather than arranging for it to be copied to its real prefix.

**Comment by stsp** [comment]
Yes. it seems to be trying to build libgcc after the
installation to DESTDIR, and that fails.
Or is this wrong and it should build libgcc before
the DESTDIR install?

**Comment by stsp** [comment]
> May I know what method you are using to specify $(prefix) and $(DESTDIR) to the GCC scripts?

DESTDIR is just exported as a variable.
I do not pass it in any other way.
prefix is being passed to configure.
Is this correct?

**Comment by skitt** [comment]
> Yes. it seems to be trying to build libgcc after the
> installation to DESTDIR, and that fails.
> Or is this wrong and it should build libgcc before
> the DESTDIR install?

I run `make`, and then `make install install-lto-plugin DESTDIR=...`, and it all builds fine. `libgcc` is built during the first part (`make`).

**Comment by stsp** [comment]
Interestingly, for me that worked only if I
already had djgpp installed system-wide.
Then it used that for libgcc, not the one in DESTDIR.
And I erased the system-wide install, after
which it broke.
I'll try again and provide more details.

**Comment by skitt** [comment]
> > I’m not sure it’s possible to run gcc somewhere other than its target installation location.
> 
> You mean, `--sysroot=` is hopeless even if you
> are not building the gcc suite, but also when you use
> it? So is it completely unrelocatable? As my impression
> was that `--sysroot=` _could_ work, if not for the
> absolute pathes in `-B` and `-isystem`.

I’ve never been particularly enthused by `--sysroot`, so I avoid it. According to the documentation, the headers and libraries should be relocatable, but I’m not sure whether that applies to `/usr/lib/gcc` too.

> > The only reliable approach for an “all-in-one” build would be
> > to configure gcc for a real installation in DESTDIR, and then
> > reconfigure and rebuild it for the target...
> 
> Could you please explain what exactly is to do here?
> Should I first include DESTDIR into prefix, and then
> not include? I probably can build gcc with the prefix
> that includes DESTDIR (not that I succeeded from
> the first try though), but when I reconfigure it with the
> right prefix, how would I rebuild? I guess you mean
> something else though, please clarify.

I was thinking that if you want to build a usable GCC during a build, which can run before it’s installed (as a package or whatever), the best approach might be to build it with a prefix corresponding to the temporary location you want to use, and install it there; that way you know it will run properly. You can also build a second copy with the intended prefix, and install it with `DESTDIR`, for use in the final output.

> Looks like we are trying to solve the problems
> that are not ours...

I’m not sure there really *is* a problem. `DESTDIR` is only intended to provide a way of “installing” programs somewhere other than their real installation target, but only for purposes of repackaging; there’s never a guarantee that a program installed with `DESTDIR` other than `/` will work as-is, before it’s moved into its real installation location.

**Comment by skitt** [comment]
> Interestingly, for me that worked only if I
> already had djgpp installed system-wide.
> Then it used that for libgcc, not the one in DESTDIR.
> And I erased the system-wide install, after
> which it broke.
> I'll try again and provide more details.

Yes, that’s normal: `libgcc` isn’t built in a stage 1 compiler, it needs the target C library in the expected location. It doesn’t take `DESTDIR` into account for this.

**Comment by stsp** [comment]
> It doesn’t take DESTDIR into account for this.

I am a bit confused, so is this normal?
What should I do to get the build done then?

**Comment by tkchia** [comment]
Hello @skitt,

> As I understand it, @stsp is trying to install GCC using `DESTDIR`, and then run it from there rather than arranging for it to be copied to its real prefix.

Thanks.  It seems I misunderstood the problem at hand.

> I run `make`, and then `make install install-lto-plugin DESTDIR=...`, and it all builds fine. libgcc is built during the first part (`make`).

Yes, this is what I am experiencing too --- and apparently, also what happens in my Launchpad builds.

Thank you!

**Comment by tkchia** [comment]
Hello @skitt, hello @stsp,

From what I see, the stage 1 build of GCC will build `libgcc` using the copy of GCC in the _build_ tree (i.e. the working directory where `configure` was launched from).

Thank you!

**Comment by tkchia** [comment]
Hello @stsp,

So --- assuming that you wish to compile some target library `libfoo` without actually installing GCC, perhaps a workable way would be to follow what the GCC code itself does when compiling `libgcc`.

I.e. build GCC in the build directory, but do _not_ install it anywhere, and instead run _build-dir_`/gcc/xgcc` with appropriate `-B`... and `-isystem` ... options.

Thank you!

**Comment by skitt** [comment]
Hello @tkchia,

> From what I see, the stage 1 build of GCC will build `libgcc` using the copy of GCC in the _build_ tree (i.e. the working directory where `configure` was launched from).

Yes, indeed; the more complicated part is convincing it to build using a C library that’s not in the standard location (that’s what I use a spec file for when building MinGW-w64, although the initial driver for that was so that we always end up using the new `crt0` & co., never the already-installed ones if there are any). I like your idea of using `xgcc`!

**Comment by stsp** [comment]
OK, I tried on my fedora machine and
that seems to work. I'll see tomorrow why
I didn't succeed on an ubuntu machine.
Thanks!

**Comment by stsp** [comment]
So while it works the way you described on fedora,
on ubuntu I am getting this:
```
/home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/./gcc/xgcc -B/home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/./gcc/ -B/usr/local/cross/i586-pc-msdosdjgpp/bin/ -B/usr/local/cross/i586-pc-msdosdjgpp/lib/ -isystem /usr/local/cross/i586-pc-msdosdjgpp/include -isystem /usr/local/cross/i586-pc-msdosdjgpp/sys-include    -g -O2 -O2  -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector -Dinhibit_libc  -I. -I. -I../.././gcc -I../../../gnu/gcc-9.2.0/libgcc -I../../../gnu/gcc-9.2.0/libgcc/. -I../../../gnu/gcc-9.2.0/libgcc/../gcc -I../../../gnu/gcc-9.2.0/libgcc/../include  -DHAVE_CC_TLS -DUSE_EMUTLS -o _ucmpdi2.o -MT _ucmpdi2.o -MD -MP -MF _ucmpdi2.dep -DL_ucmpdi2 -c ../../../gnu/gcc-9.2.0/libgcc/libgcc2.c 
```
```
In file included from ../../../gnu/gcc-9.2.0/libgcc/../gcc/tsystem.h:45,
                 from ../../../gnu/gcc-9.2.0/libgcc/libgcc2.c:27:
/home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/gcc/include/float.h:29:15: fatal error: float.h: No such file or directory
   29 | #include_next <float.h>
      |               ^~~~~~~~~
compilation terminated.
In file included from ../../../gnu/gcc-9.2.0/libgcc/../gcc/tsystem.h:45,
                 from ../../../gnu/gcc-9.2.0/libgcc/libgcc2.c:27:
/home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/gcc/include/float.h:29:15: fatal error: float.h: No such file or directory
   29 | #include_next <float.h>
      |               ^~~~~~~~~
In file included from ../../../gnu/gcc-9.2.0/libgcc/../gcc/tsystem.h:45,
                 from ../../../gnu/gcc-9.2.0/libgcc/libgcc2.c:27:
/home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/gcc/include/float.h:29:15: fatal error: float.h: No such file or directory
   29 | #include_next <float.h>
      |               ^~~~~~~~~
In file included from ../../../gnu/gcc-9.2.0/libgcc/../gcc/tsystem.h:45,
                 from ../../../gnu/gcc-9.2.0/libgcc/libgcc2.c:27:
/home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/gcc/include/float.h:29:15: fatal error: float.h: No such file or directory
   29 | #include_next <float.h>
```

Not sure what is the difference with the fedora machine...

**Comment by stsp** [comment]
/home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/./gcc/xgcc -B/home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/./gcc/ -B/usr/local/cross/i586-pc-msdosdjgpp/bin/ -B/usr/local/cross/i586-pc-msdosdjgpp/lib/ -isystem /usr/local/cross/i586-pc-msdosdjgpp/include -isystem /usr/local/cross/i586-pc-msdosdjgpp/sys-include    -g -O2 -O2  -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector -Dinhibit_libc  -I. -I. -I../.././gcc -I../../../gnu/gcc-9.2.0/libgcc -I../../../gnu/gcc-9.2.0/libgcc/. -I../../../gnu/gcc-9.2.0/libgcc/../gcc -I../../../gnu/gcc-9.2.0/libgcc/../include  -DHAVE_CC_TLS -DUSE_EMUTLS -o _ucmpdi2.o -MT _ucmpdi2.o -MD -MP -MF _ucmpdi2.dep -DL_ucmpdi2 -c ../../../gnu/gcc-9.2.0/libgcc/libgcc2.c

**Comment by stsp** [comment]
To me, the problem in the above, is
`-isystem /usr/local/cross/i586-pc-msdosdjgpp/include -isystem /usr/local/cross/i586-pc-msdosdjgpp/sys-include`.

So while it takes the binary from the build dir just
as you said, it expects the headers in the prefix.
Any possible explanation to that?

**Comment by tkchia** [comment]
Hello @stsp,

> ```
> In file included from ../../../gnu/gcc-9.2.0/libgcc/../gcc/tsystem.h:45,
>                  from ../../../gnu/gcc-9.2.0/libgcc/libgcc2.c:27:
> /home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/gcc/include/float.h:29:15: fatal error: float.h: No such file or directory
>    29 | #include_next <float.h>
> ```

Hmm... the strange thing to me is that there is an `#include_next` at all.  The `gcc/include/float.h` in both my stage 1 and stage 2 builds of `gcc-ia16` only define a bunch of macros (this is for GCC 6.3.0 though, which may be different from GCC 9):
```
...
/*
 * ISO C Standard:  5.2.4.2.2  Characteristics of floating types <float.h>
 */

#ifndef _FLOAT_H___
#define _FLOAT_H___

/* Radix of exponent representation, b. */
#undef FLT_RADIX
#define FLT_RADIX       __FLT_RADIX__

/* Number of base-FLT_RADIX digits in the significand, p.  */
#undef FLT_MANT_DIG
#undef DBL_MANT_DIG
#undef LDBL_MANT_DIG
#define FLT_MANT_DIG    __FLT_MANT_DIG__
#define DBL_MANT_DIG    __DBL_MANT_DIG__
#define LDBL_MANT_DIG   __LDBL_MANT_DIG__
...
#ifdef __STDC_WANT_DEC_FP__
/* Draft Technical Report 24732, extension for decimal floating-point
   arithmetic: Characteristic of decimal floating types <float.h>.  */

/* Number of base-FLT_RADIX digits in the significand, p.  */
#undef DEC32_MANT_DIG
#undef DEC64_MANT_DIG
#undef DEC128_MANT_DIG
#define DEC32_MANT_DIG  __DEC32_MANT_DIG__
#define DEC64_MANT_DIG  __DEC64_MANT_DIG__
#define DEC128_MANT_DIG __DEC128_MANT_DIG__
...
#undef DEC_EVAL_METHOD
#define DEC_EVAL_METHOD __DEC_EVAL_METHOD__

#endif /* __STDC_WANT_DEC_FP__ */

#endif /* _FLOAT_H___ */
```
A few things you can perhaps try checking:
  * Does the `gcc/include/float.h` in your Fedora build also have an `#include_next` in it?
  * Are there any notable differences in the auto-detected `configure` settings, between the Fedora build and the Ubuntu build?

> To me, the problem in the above, is
> `-isystem /usr/local/cross/i586-pc-msdosdjgpp/include -isystem /usr/local/cross/i586-pc-msdosdjgpp/sys-include`.

The include files that `libgcc` needs should all come from first `-B`... path, i.e. within `home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/./gcc/`.

Thank you!

**Comment by stsp** [comment]
Whoa!
```
#ifdef __DJGPP__
#include_next <float.h>
#endif
```

So thanks for the hint, and let me see where this
one came from. :)

**Comment by stsp** [comment]
Now this:
```
In file included from ../../../gnu/gcc-9.2.0/libquadmath/math/x2y2m1q.c:19:
../../../gnu/gcc-9.2.0/libquadmath/quadmath-imp.h:24:10: fatal error: errno.h: No such file or directory
   24 | #include <errno.h>
      |          ^~~~~~~~~
```

Any hints? :)

**Comment by stsp** [comment]
So would it be correct to assume that gcc
may need the system headers during build,
and so removing the `include_next` patch
from build was not the right fix?

**Comment by stsp** [comment]
Indeed, if I "fix" `-isystem` then that part builds.
And in Makefile of libquadmath I have:

CC = /home/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/./gcc/xgcc -B/home
/stas/src/build-gcc/build/djcross-gcc-9.2.0/djcross/./gcc/ -B/usr/local/cross/i5
86-pc-msdosdjgpp/bin/ -B/usr/local/cross/i586-pc-msdosdjgpp/lib/ -isystem /usr/l
ocal/cross/i586-pc-msdosdjgpp/include -isystem /usr/local/cross/i586-pc-msdosdjg
pp/sys-include

**Comment by stsp** [comment]
Can someone please see the same in your Makefile?
(I'll look that up on fedora machine too, but they are
not available to me simultaneously).

**Comment by stsp** [comment]
So it doesn't have anything to do with fedora
or ubuntu. Just on fedora it appears I had 2 installs:
from rpm and local. And removed only one before
experimenting. Now I removed the second install
and am experiencing exactly the same problem as
on ubuntu.
So could you guys please see how you get the
libquadmath built? For me it requires the headers
in prefix.

**Comment by stsp** [comment]
Can build with this:
```
--- configure.ac.old    2019-09-24 03:44:28.141779422 +0300
+++ configure.ac        2019-09-24 03:30:59.022308759 +0300
@@ -2572,7 +2572,7 @@

 # Some systems (e.g., one of the i386-aix systems the gas testers are
 # using) don't handle "\$" correctly, so don't use it here.
-tooldir='${exec_prefix}'/${target_noncanonical}
+tooldir='${DESTDIR}${exec_prefix}'/${target_noncanonical}
 build_tooldir=${tooldir}

 # Create a .gdbinit file which runs the one in srcdir
```

So really is the gcc bug it seems.

**Comment by stsp** [comment]
With some help of gcc guys I am getting closer.
Now I have a debuild question.
It seems it sets DESTDIR before "make install".
Is it possible to access that path from the
`override_dh_auto_configure:` section?
"make install" is too late for me, I need to know
the DESTDIR path on configure stage.

**Comment by skitt** [comment]
In Debian builds, tools which set `DESTDIR` (such as [`dh_auto_install`](https://manpages.debian.org/dh_auto_install)) set it to either `debian/package` (for single-package builds) or `debian/tmp` (for multi-package builds). You can run other parts of the build with `DESTDIR` manually set to the appropriate value.

**Comment by stsp** [comment]
Looks like I've succeeded (somewhat) with the
2-staged build scenario. Horribly difficult stuff. :(

**Comment by stsp** [comment]
Now I have the following problem.
I can fully build gcc and libs in some temporary
stash by using `--with-prefix=`. Then I am trying
to build the second gcc by the use of these tools.
I use `--with-build-time-tools=` for that.
This option finds the pre-built tools successfully,
but uses only _some_ of them (as, ld). It still
insists on using the local xgcc for cross-compile.
How to convince it to use pre-built cross gcc?

**Comment by stsp** [comment]
I think I have finally fixed the gcc build system bug:
https://github.com/stsp/build-gcc/commit/ec46005a6a62b56e29c7d4f2e03dbb778a2e0eac
And I have an impression that now I am much
closer to the solution. But of course this may
turn out false assumption...
